package com.hadoop.leftouterjoin;

import org.apache.hadoop.fs.FileSystem;
import org.apache.hadoop.fs.Path;
import org.apache.hadoop.io.Text;
import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.mapreduce.Job;
import org.apache.hadoop.mapreduce.lib.input.MultipleInputs;
import org.apache.hadoop.mapreduce.lib.input.TextInputFormat;
import org.apache.hadoop.mapreduce.lib.output.FileOutputFormat;
import org.apache.hadoop.mapreduce.lib.output.SequenceFileOutputFormat;
import edu.umd.cloud9.io.pair.PairOfStrings;



/**
 * Created with IDEA by ChouFy on 2019/6/18.
 *
 * @author Zhoufy
 */
public class LeftJoinDriver {

    public static void main( String[] args ) throws Exception {
        // input
        Path transactions = new Path(args[0]);
        // input
        Path users = new Path(args[1]);
        // output
        Path output = new Path(args[2]);


        Configuration conf = new Configuration();

        FileSystem file = FileSystem.get(conf);
        if (file.exists(output)) {
            file.deleteOnExit(output);
        }
        file.close();

        Job job = Job.getInstance(conf);
        job.setJarByClass(LeftJoinDriver.class);
        job.setJobName("Phase-1: Left Outer Join");

        // "secondary sort" is handled by setting the following 3 plug-ins:
        // 1. how the mapper generated keys will be partitioned
        job.setPartitionerClass(SecondarySortPartitioner.class);

        // 2. how the natural keys (generated by mappers) will be grouped
        job.setGroupingComparatorClass(SecondarySortGroupComparator.class);

        // 3. how PairOfStrings will be sorted
        job.setSortComparatorClass(PairOfStrings.Comparator.class);

        job.setReducerClass(LeftJoinReducer.class);

        job.setOutputKeyClass(Text.class);
        job.setOutputValueClass(Text.class);
        job.setOutputFormatClass(SequenceFileOutputFormat.class);

        // define multiple mappers: one for users and one for transactions
        // 可以指定多个输入路径，每个路径都可以指定相应的map方法
        MultipleInputs.addInputPath(job, transactions, TextInputFormat.class, LeftJoinTransactionMapper.class);
        MultipleInputs.addInputPath(job, users, TextInputFormat.class, LeftJoinUserMapper.class);

        job.setMapOutputKeyClass(PairOfStrings.class);
        job.setMapOutputValueClass(PairOfStrings.class);
        FileOutputFormat.setOutputPath(job, output);

        if (job.waitForCompletion(true)) {
            return;
        }
        else {
            throw new Exception("Phase-1: Left Outer Join Job Failed");
        }
    }
}
